repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/jorisroovers/gitlint
  rev:  v0.15.1
  hooks:
  - id: gitlint
    stages: [commit-msg]

- repo: https://github.com/ambv/black
  rev: 21.7b0
  hooks:
  - id: black
    language_version: python3.9

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]

- repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
    - id: go-fmt
    - id: go-lint
    - id: go-imports
