[book]
authors = ["Andreas Peters"]
language = "en"
multilingual = false
src = "src"
title = "M3S - Apache Mesos Kubernetes Framework"

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/AVENTER-UG/go-mesos-framework-k3s"
